var dir_e2489e887f17afa3cbc07a4ec152cdd2 =
[
    [ "adsr.h", "adsr_8h.html", "adsr_8h" ],
    [ "atanLUT.h", "atanLUT_8h.html", "atanLUT_8h" ],
    [ "display.h", "display_8h.html", "display_8h" ],
    [ "distortion.h", "distortion_8h.html", "distortion_8h" ],
    [ "drum_computer.h", "drum__computer_8h.html", "drum__computer_8h" ],
    [ "effects.h", "effects_8h.html", "effects_8h" ],
    [ "emg.h", "emg_8h.html", "emg_8h" ],
    [ "fatfs_sd.h", "fatfs__sd_8h.html", null ],
    [ "filters.h", "filters_8h.html", "filters_8h" ],
    [ "input_interfaces.h", "input__interfaces_8h.html", "input__interfaces_8h" ],
    [ "keyboard.h", "keyboard_8h.html", "keyboard_8h" ],
    [ "main.h", "main_8h.html", "main_8h" ],
    [ "math_helper.h", "math__helper_8h_source.html", null ],
    [ "music_notes.h", "music__notes_8h.html", "music__notes_8h" ],
    [ "sd_card.h", "sd__card_8h.html", null ],
    [ "signal_synthesis.h", "signal__synthesis_8h.html", "signal__synthesis_8h" ],
    [ "sinLUT.h", "sinLUT_8h.html", "sinLUT_8h" ],
    [ "SPI_Connection.h", "SPI__Connection_8h.html", "SPI__Connection_8h" ],
    [ "stm32f7xx_hal_conf.h", "stm32f7xx__hal__conf_8h_source.html", null ],
    [ "stm32f7xx_it.h", "stm32f7xx__it_8h.html", "stm32f7xx__it_8h" ],
    [ "tremolo.h", "tremolo_8h.html", "tremolo_8h" ],
    [ "wahwah.h", "wahwah_8h.html", "wahwah_8h" ],
    [ "wav.h", "wav_8h.html", "wav_8h" ],
    [ "wav_LUT.h", "wav__LUT_8h.html", null ]
];