var dir_b596f468b52957496e4f78b80e029268 =
[
    [ "adsr.c", "adsr_8c.html", "adsr_8c" ],
    [ "display.c", "display_8c.html", "display_8c" ],
    [ "distortion.c", "distortion_8c.html", "distortion_8c" ],
    [ "drum_computer.c", "drum__computer_8c.html", "drum__computer_8c" ],
    [ "effects.c", "effects_8c.html", "effects_8c" ],
    [ "emg.c", "emg_8c.html", "emg_8c" ],
    [ "fatfs_sd.c", "fatfs__sd_8c.html", null ],
    [ "filters.c", "filters_8c.html", "filters_8c" ],
    [ "input_interfaces.c", "input__interfaces_8c.html", "input__interfaces_8c" ],
    [ "keyboard.c", "keyboard_8c.html", "keyboard_8c" ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "music_notes.c", "music__notes_8c.html", "music__notes_8c" ],
    [ "sd_card.c", "sd__card_8c.html", null ],
    [ "signal_synthesis.c", "signal__synthesis_8c.html", "signal__synthesis_8c" ],
    [ "sinLUT.c", "sinLUT_8c.html", null ],
    [ "SPI_Connection.c", "SPI__Connection_8c.html", "SPI__Connection_8c" ],
    [ "stm32f7xx_hal_msp.c", "stm32f7xx__hal__msp_8c_source.html", null ],
    [ "stm32f7xx_it.c", "stm32f7xx__it_8c.html", "stm32f7xx__it_8c" ],
    [ "syscalls.c", "syscalls_8c_source.html", null ],
    [ "sysmem.c", "sysmem_8c_source.html", null ],
    [ "tremolo.c", "tremolo_8c.html", "tremolo_8c" ],
    [ "wahwah.c", "wahwah_8c.html", "wahwah_8c" ],
    [ "wav_LUT.c", "wav__LUT_8c.html", null ]
];